version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - getir-net

  getir-kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: getir-kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://getir-kafka:9092,PLAINTEXT_HOST://getir-kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - getir-kafka-volume:/var/lib/kafka/data
    networks:
      - getir-net

  getir-mysql:
    image: mysql:8.0
    volumes:
      - getir-mysql-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=GETIR
      - MYSQL_USER=READING_IS_GOOD_USER
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    networks:
      - getir-net

  getir-redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - getir-redis-volume:/data

  reading-is-good:
    image: reading-is-good-image:latest
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - getir-net

volumes:
  getir-mysql-volume:
  getir-kafka-volume:
  getir-redis-volume:
networks:
  getir-net:
    driver: bridge