server:
  port: '8080'
management:
  server:
    port: '8081'
spring:

  application:
    name: READING-IS-GOOD
  cloud:
    config:
      enabled: false
  kafka:
    consumer:
      group-id: reading-is-good
      auto-offset-reset: latest
    bootstrap-servers: getir-kafka:29092
    topic:
      statistic: statistic
  redis:
    host: getir-redis
    port: 6379
    connect-timeout: 60
    database: 0
    password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  flyway:
    schemas: GETIR
    user: root
    password: root
    url: jdbc:mysql://getir-mysql:3306/mysql
    enabled: true
    baseline-on-migrate: true
  jpa:
    defer-datasource-initialization: 'false'
    show-sql: 'true'
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    password: password
    username: READING_IS_GOOD_USER
    url: jdbc:mysql://getir-mysql:3306/GETIR?useSSL=false&allowPublicKeyRetrieval=true
  health:
    circuitbreakers:
      enabled: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
resilience4j.circuitbreaker:
  instances:
    myProjectAllRemoteCallsCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      slidingWindowType: COUNT_BASED
      permittedNumberOfCallsInHalfOpenState: 4
      minimumNumberOfCalls: 10
      waitDurationInOpenState: 5s
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 10
      failureRateThreshold: 50